merge_EIP/Models/Funding.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace merge_EIP.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Funding
    {
        public int applicationNumber { get; set; }
        [Display(Name = "員工編號")]
        public string employeeID { get; set; }
        [Display(Name = "姓名")]
        public string employeeName { get; set; }
        [Display(Name = "申請金額")]
        public int applicationAmount { get; set; }
        [Display(Name = "類別")]
        public string Type { get; set; }
        [Display(Name = "狀態")]
        public string State { get; set; }
        [Display(Name = "原因")]
        public string Reason { get; set; }

        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd hh:mm}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> submitDate { get; set; }

        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> Auditdate { get; set; }
        public Nullable<bool> fcheck { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}

merge_EIP/Models/Search.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace merge_EIP.Models
{
    public class Search
    {
        public List<dayOff> leave { get; set; }
        public List<Funding> budget { get; set; }
        public List<workOvertime> OT { get; set; }
        public List<rePunchin> repunch { get; set; }
    }
}

merge_EIP/Controllers/FormController.cs
using merge_EIP.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace merge_EIP.Controllers
{
    public class FormController : Controller
    {
        FormModelEntities db = new FormModelEntities();

        // GET - 表單申請
        public ActionResult Leave()
        {
            return View();
        }

        // POST - 表單申請
        [HttpPost]
        public ActionResult Leave(dayOff tdayOff)
        {
            tdayOff.State = "審核中";
            tdayOff.employeeID = Session["ID"].ToString();
            tdayOff.employeeName = Session["Name"].ToString();
            tdayOff.submitDate = DateTime.Now;

            var start = Convert.ToDateTime(tdayOff.startDate);
            var end = Convert.ToDateTime(tdayOff.endDate);

            var temp = Convert.ToInt32(new TimeSpan(end.Ticks - start.Ticks).TotalHours);

            var d = (temp / 24).ToString();
            var h = (temp % 24).ToString();
            tdayOff.totalDay = $"{d}日 {h}時";

            // 上傳檔案
            if (tdayOff.ImageFile != null)
            {
                string fileName = Path.GetFileNameWithoutExtension(tdayOff.ImageFile.FileName);
                string extension = Path.GetExtension(tdayOff.ImageFile.FileName);
                fileName = DateTime.Now.ToString("yymmssfff") + extension;
                tdayOff.filePath = "~/Image/" + fileName;
                fileName = Path.Combine(Server.MapPath("~/Image"), fileName);
                tdayOff.ImageFile.SaveAs(fileName);
            }

            db.dayOff.Add(tdayOff);
            db.SaveChanges();

            Session["mypost"] = "FOK";

            return RedirectToAction("Search");
        }

        // 附件檔案
        public ActionResult Img(int? fId)
        {
            if (Session["ID"] != null)
            {
                dayOff image = new dayOff();
                image = db.dayOff.Where(m => m.dayoffNumber == fId).FirstOrDefault();

                return View(image);
            }
            else
            {
                return RedirectToAction("Search");
            }
        }

        // GET - 加班單申請
        public ActionResult Overtime()
        {
            return View();
        }

        //POST - 加班單申請
        [HttpPost]
        public ActionResult Overtime(workOvertime tworkOvertime)
        {
            tworkOvertime.State = "審核中";
            tworkOvertime.employeeID = Session["ID"].ToString();
            tworkOvertime.employeeName = Session["Name"].ToString();
            tworkOvertime.submitDate = DateTime.Now;

            var start = tworkOvertime.startTime.ToString();
            var end = tworkOvertime.expectTime.ToString();

            var int_time = Convert.ToDecimal((DateTime.Parse(end) - DateTime.Parse(start)).TotalHours);

            var temp = int_time % 100;
            tworkOvertime.overtimeHours = $"{temp.ToString("F2")} 小時";

            db.workOvertime.Add(tworkOvertime);
            db.SaveChanges();
            Session["mypost"] = "FOK";
            return RedirectToAction("Search");
        }

        // GET - 經費申請
        public ActionResult Funding()
        {
            return View();
        }

        // POST - 經費申請
        [HttpPost]
        public ActionResult Funding(Funding tfunding)
        {
            tfunding.State = "審核中";
            tfunding.employeeID = Session["ID"].ToString();
            tfunding.employeeName = Session["Name"].ToString();
            tfunding.submitDate = DateTime.Now;

            db.Funding.Add(tfunding);
            db.SaveChanges();
            Session["mypost"] = "FOK";
            return RedirectToAction("Search");
        }

        // GET - 補打卡
        public ActionResult rePunch()
        {
            return View();
        }

        // POST - 補打卡
        [HttpPost]
        public ActionResult rePunch(rePunchin trePunchin)
        {
            trePunchin.State = "審核中";
            trePunchin.employeeID = Session["ID"].ToString();
            trePunchin.employeeName = Session["Name"].ToString();
            trePunchin.submitDate = DateTime.Now;

            if (trePunchin.Reason == null)
            {
                trePunchin.Reason = "無備註";
            }

            db.rePunchin.Add(trePunchin);
            db.SaveChanges();
            Session["mypost"] = "FOK";
            return RedirectToAction("Search");
        }

        // 員工查詢
        public ActionResult Search(int? id, string type)
        {
            // 判斷是否有登入
            if (Session["ID"] != null)
            {
                //if(id != null)
                //{
                //    if(type == "請假")
                //    {
                        
                //    }else if(type == "加班")
                //    {
                        
                //    }else if(type == "經費")
                //    {

                //    }else if(type == "補卡")
                //    {

                //    }
                //}

                string posID = Convert.ToString(Session["PosID"]);
                if (posID == "1")
                {
                    var EID = Convert.ToString(Session["ID"]);
                    var lv = db.dayOff.Where(m => m.employeeID == EID).OrderByDescending(m => m.dayoffNumber).ToList();
                    var bd = db.Funding.Where(m => m.employeeID == EID).OrderByDescending(m => m.applicationNumber).ToList();
                    var ot = db.workOvertime.Where(m => m.employeeID == EID).OrderByDescending(m => m.overtimeNumber).ToList();
                    var re = db.rePunchin.Where(m => m.employeeID == EID).OrderByDescending(m => m.repunchID).ToList();

                    Search all = new Search() { leave = lv, budget = bd, OT = ot, repunch = re };
                    return View(all);
                }
                else
                {
                    return RedirectToAction("Approve");
                }
            }
            else
            {
                return RedirectToAction("Logout", "Login");
            }
        }

        // 測試員工查詢
        public ActionResult FSearch()
        {
            // 判斷是否有登入
            if (Session["ID"] != null)
            {
                string posID = Convert.ToString(Session["PosID"]);
                if (posID == "1")
                {
                    var id = Convert.ToString(Session["ID"]);
                    var lv = db.dayOff.Where(m => m.employeeID == id).OrderByDescending(m => m.dayoffNumber).ToList();
                    var bd = db.Funding.Where(m => m.employeeID == id).OrderByDescending(m => m.applicationNumber).ToList();
                    var ot = db.workOvertime.Where(m => m.employeeID == id).OrderByDescending(m => m.overtimeNumber).ToList();
                    var re = db.rePunchin.Where(m => m.employeeID == id).OrderByDescending(m => m.repunchID).ToList();

                    Search all = new Search() { leave = lv, budget = bd, OT = ot, repunch = re };
                    return View(all);
                }
                else
                {
                    return RedirectToAction("Approve");
                }
            }
            else
            {
                return RedirectToAction("Logout", "Login");
            }
        }

        // 老闆審核
        public ActionResult Approve()
        {
            if (Session["ID"] != null)
            {
                string posID = Convert.ToString(Session["PosID"]);
                string Dep = Convert.ToString(Session["Dep"]);

                if (posID == "0")
                {
                    // 判斷同部門的上司才可以看得到自己的審核
                    var lv = db.dayOff.Where(m => m.State.Contains("審核") && m.Employee.Department.departmentName == Dep).ToList();
                    var bd = db.Funding.Where(m => m.State.Contains("審核") && m.Employee.Department.departmentName == Dep).ToList();
                    var ot = db.workOvertime.Where(m => m.State.Contains("審核") && m.Employee.Department.departmentName == Dep).ToList();
                    var re = db.rePunchin.Where(m => m.State.Contains("審核") && m.Employee.Department.departmentName == Dep).ToList();

                    int lv_qty = lv.Count;
                    int bd_qty = bd.Count;
                    int ot_qty = ot.Count;
                    int re_qty = re.Count;

                    foreach (var item in lv)
                    {
                        // 上傳檔案
                        if (item.filePath == null)
                        {
                            item.filePath = "";
                        }
                        else
                        {
                            item.filePath = "查看附件";
                        }
                    }

                    ViewBag.lv_qty = lv_qty;
                    ViewBag.bd_qty = bd_qty;
                    ViewBag.ot_qty = ot_qty;
                    ViewBag.re_qty = re_qty;

                    Search all = new Search() { leave = lv, budget = bd, OT = ot, repunch = re };
                    return View(all);
                }
                else
                {
                    return RedirectToAction("Search");
                }
            }
            else
            {
                return RedirectToAction("Logout", "Login");
            }
        }

        // 假單同意
        public ActionResult Yes(int fId)
        {
            var temp = db.dayOff.Where(m => m.dayoffNumber == fId).FirstOrDefault();
            temp.State = "同意";
            temp.Auditdate = DateTime.Today;
            temp.fcheck = false;

            for (DateTime i = temp.startDate.Date; i <= temp.endDate.Date; i = i.AddDays(1))
            {
                string thisTime = i.ToString("yyyy-MM-dd");
                var Yestemp = db.punchIn.Where(x => x.punchinDate.ToString().Contains(thisTime) && x.employeeID == temp.employeeID).FirstOrDefault();
                if (temp.Type == "公差")
                {

merge_EIP/Views/Form/Approve.cshtml
@model merge_EIP.Models.Search
@{
    ViewBag.Title = "Approve";
}
@functions{
    public string showCnt(string x)
    {
        if (Convert.ToInt32(x) >= 1)
        {
            return x;
        }
        else
        {
            return "";
        }
    }
}

<style>
    .swal-wide {
        width: 800px;
    }

    .swal2-popup {
        width: 50em;
    }

    .sweet-alert .sa-icon {
        max-width: 800px;
        max-height: 800px;
    }
</style>

<div class="container">
    <br />
    <h2 class="font-weight-bold">表單審核</h2>
    <div class="btn-group" role="group" aria-label="Basic example">
        <button type="button" class="btn btn-FB" onclick="showT1()">
            假單
            <span class="badge badge-pill badge-warning">@showCnt($"{ViewBag.lv_qty}")</span>
        </button>
        <button type="button" class="btn btn-FB" onclick="showT2()">
            加班單
            <span class="badge badge-pill badge-warning">@showCnt($"{ViewBag.ot_qty}")</span>
        </button>
        <button type="button" class="btn btn-FB" onclick="showT3()">
            補卡單
            <span class="badge badge-pill badge-warning">@showCnt($"{ViewBag.re_qty}")</span>
        </button>
        <button type="button" class="btn btn-FB" onclick="showT4()">
            經費申請單
            <span class="badge badge-pill badge-warning">@showCnt($"{ViewBag.bd_qty}")</span>
        </button>
    </div>
    <br />
    <br />


    <div id="showT1">
        <h3>假單審核</h3>
        <p>待審核假單共 @ViewBag.lv_qty 筆</p>
        <a href="@Url.Action("AllYes")" class="float-right btn btn-FB" onclick="return YNbtn(event,'同意','請假全部')" style="white-space: nowrap;">一鍵同意</a>
        <div class="table-responsive">
            <table class="table" id="sort-table">
                <thead>
                    <tr>
                        <th data-sortable="true">申請時間</th>
                        <th data-sortable="true">員工編號</th>
                        <th data-sortable="true">姓名</th>
                        <th data-sortable="true">假別</th>
                        <th data-sortable="true">起始日</th>
                        <th data-sortable="true">結束日</th>
                        <th data-sortable="true">合計</th>
                        <th data-sortable="true">理由</th>
                        <th data-sortable="true">附件</th>
                        <th data-sortable="true">審核</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model.leave)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.submitDate)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.employeeID)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.employeeName)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Type)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.startDate)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.endDate)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.totalDay)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Reason)
                            </td>
                            <td>
                                <a href="@Url.Action("Img")?fId=@item.dayoffNumber" data-fid='@item.dayoffNumber' onclick="return showIMG(event, '@item.employeeName')">
                                    @Html.DisplayFor(modelItem => item.filePath)
                                </a>
                            </td>
                            <td>
                                <a href="@Url.Action("Yes")?fId=@item.dayoffNumber" class="btn btn-FB m-1" onclick="return YNbtn(event,'同意','@item.employeeName')" style="white-space: nowrap;">同意</a>
                                <a href="@Url.Action("No")?fId=@item.dayoffNumber" class="btn btn-secondary m-1" onclick="return YNbtn(event,'退回','@item.employeeName')" style="white-space: nowrap;">退回</a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>

    <div id="showT2" style="display:none">
        <h3>加班單審核</h3>
        <p>待審核加班單共 @ViewBag.ot_qty 筆</p>
        <a href="@Url.Action("AllOTYes")" class="float-right btn btn-FB" onclick="return YNbtn(event,'同意','加班全部')" style="white-space: nowrap;">一鍵同意</a>
        <div class="table-responsive">
            <table class="table" id="sort-table2">
                <thead>
                    <tr>
                        <th data-sortable="true">員工編號</th>
                        <th data-sortable="true">姓名</th>
                        <th data-sortable="true">日期</th>
                        <th data-sortable="true">開始時間</th>
                        <th data-sortable="true">結束時間</th>
                        <th data-sortable="true">合計小時</th>
                        <th data-sortable="true">備註</th>
                        <th data-sortable="true">審核</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model.OT)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.employeeID)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.employeeName)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Date)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.startTime)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.expectTime)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.overtimeHours)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Reason)
                            </td>
                            <td>
                                <a href="@Url.Action("OTYes")?fId=@item.overtimeNumber" class="btn btn-FB m-1" onclick="return YNbtn(event,'同意','@item.employeeName')" style="white-space: nowrap;">同意</a>
                                <a href="@Url.Action("OTNo")?fId=@item.overtimeNumber" class="btn btn-secondary m-1" onclick="return YNbtn(event,'退回','@item.employeeName')" style="white-space: nowrap;">退回</a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>

    <div id="showT3" style="display:none">
        <h3>補卡審核</h3>
        <p>待審核補卡共 @ViewBag.re_qty 筆</p>
        <a href="@Url.Action("AllreYes")" class="float-right btn btn-FB" onclick="return YNbtn(event,'同意','補卡全部')" style="white-space: nowrap;">一鍵同意</a>
        <div class="table-responsive">
            <table class="table" id="sort-table3">
                <thead>
                    <tr>
                        <th data-sortable="true">員工編號</th>
                        <th data-sortable="true">姓名</th>
                        <th data-sortable="true">日期</th>
                        <th data-sortable="true">上班打卡時間</th>
                        <th data-sortable="true">下班打卡時間</th>
                        <th data-sortable="true">備註</th>
                        <th data-sortable="true">審核</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model.repunch)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.employeeID)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.employeeName)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.repunchdate)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.repunchTimeIn)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.repunchTimeOut)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Reason)
                            </td>
                            <td>
                                <a href="@Url.Action("reYes")?fId=@item.repunchID" class="btn btn-FB m-1" onclick="return YNbtn(event,'同意','@item.employeeName')" style="white-space: nowrap;">同意</a>
                                <a href="@Url.Action("reNo")?fId=@item.repunchID" class="btn btn-secondary m-1" onclick="return YNbtn(event,'退回','@item.employeeName')" style="white-space: nowrap;">退回</a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>

    <div id="showT4" style="display:none">
        <h3>經費審核</h3>
        <p>待審核經費共 @ViewBag.bd_qty 筆</p>
        <a href="@Url.Action("AllbdYes")" class="float-right btn btn-FB" onclick="return YNbtn(event,'同意','經費全部')" style="white-space: nowrap;">一鍵同意</a>
        <div class="table-responsive">
            <table class="table" id="sort-table4">
                <thead>
                    <tr>
                        <th data-sortable="true">員工編號</th>
                        <th data-sortable="true">姓名</th>
                        <th data-sortable="true">項目</th>
                        <th data-sortable="true">費用</th>
                        <th data-sortable="true">備註</th>
                        <th data-sortable="true">審核</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model.budget)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.employeeID)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.employeeName)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Type)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.applicationAmount)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Reason)
                            </td>
                            <td>
                                <a href="@Url.Action("bdYes")?fId=@item.applicationNumber" class="btn btn-FB m-1" onclick="return YNbtn(event,'同意','@item.employeeName')" style="white-space: nowrap;">同意</a>
                                <a href="@Url.Action("bdNo")?fId=@item.applicationNumber" class="btn btn-secondary m-1" onclick="return YNbtn(event,'退回','@item.employeeName')" style="white-space: nowrap;">退回</a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>

</div>

<script src="~/Scripts/Form/buttonShow.js"></script>
<script src="~/Scripts/worklog/SwalYN.js"></script>

<script src="~/Scripts/bootstrap-table.min.js"></script>
<script src="~/Scripts/colResizable/colResizable-1.6.min.js"></script>
<script src="~/Scripts/table_ALL/BStable.js"></script>

merge_EIP/Views/Form/Img.cshtml
@{
    ViewBag.Title = "查看附件";
}

@model merge_EIP.Models.dayOff

<img src="@Url.Content(Model.filePath)" />

<p>
    @Html.ActionLink("回到上一頁", "Approve")
</p>

merge_EIP/Views/Form/Leave.cshtml
@{
    ViewBag.Title = "公差假單申請表";
}
<div class="container p-33">
    <br />
    <h2>公差假單申請表</h2>
    <hr />

    @model merge_EIP.Models.dayOff

    @using (Html.BeginForm("Leave", "Form", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()
        <div class="row">
            <div class="col-12 col-xl-6">
                <div class="form-horizontal">
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    <div class="form-group">
                        @Html.LabelFor(model => model.employeeID, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Session["ID"]
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.employeeName, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Session["Name"]
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.startDate, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.startDate, new { htmlAttributes = new { @class = "form-control", type = "datetime-local", required = "required", max = "2018-06-14T00:00" } })
                            @Html.ValidationMessageFor(model => model.startDate, "", new { @class = "text-danger" })
                            @*<small>最小請假時單位為1小時</small><br />*@
                            @*，以整點、30分始計算*@
                            <small id="errSTitle" class="text-danger"></small>
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.endDate, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.endDate, new { htmlAttributes = new { @class = "form-control", type = "datetime-local", required = "required", max = "2018-06-14T00:00" } })
                            @Html.ValidationMessageFor(model => model.endDate, "", new { @class = "text-danger" })
                            <small>最小請假時單位為1小時</small><br />
                            <small id="errETitle" class="text-danger"></small>
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Type, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            <select id="fType" name="Type" class="form-control">
                                <option value="公差" name="Type" id="fType">公差</option>
                                <option value="補休">補休</option>
                                <option value="特休">特休</option>
                                <option value="傷病假">傷病假</option>
                                <option value="生理假">生理假</option>
                                <option value="公假">公假</option>
                                <option value="事假">事假</option>
                                <option value="喪假">喪假</option>
                            </select>
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-12 col-xl-6">
                <div class="form-group">
                    @Html.LabelFor(model => model.Reason, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Reason, new { htmlAttributes = new { @class = "form-control", maxlength = "200", required = "required" } })
                        @Html.ValidationMessageFor(model => model.Reason, "", new { @class = "text-danger" })
                    </div>
                </div>

                @*上傳檔案*@
                <div class="form-group">
                    @Html.LabelFor(model => model.filePath, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        <input type="file" name="ImageFile" id="FileUp" class="FileUP" />
                        <br />
                        <small>可以不附檔 ( 一次只能上傳一份，僅限jpg或png檔案 )</small>
                        <br>
                        <div>
                            <img id="preview" class="m-2" style="max-width: 200px; max-height: 200px;">
                            <div class="size"></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="申請" class="btn btn-FB FileUpBtn float-right" />
            </div>
        </div>
    }
</div>
<br />
<br />
<br />
<br />
<script>
    function GetFormattedDate(date) {
        var month = ("0" + (date.getMonth() + 1)).slice(-2);
        var day = ("0" + (date.getDate())).slice(-2);
        var year = date.getFullYear();
        var hour = ("0" + (date.getHours())).slice(-2);
        var min = ("0" + (date.getMinutes())).slice(-2);
        var seg = ("0" + (date.getSeconds())).slice(-2);
        return year + "-" + month + "-" + day + "T" + hour + ":" + min;
    }

    let maxdate = new Date();
    maxdate.setDate(maxdate.getDate() + 14);
    console.log(GetFormattedDate(maxdate))
    $("#startDate").attr("max", GetFormattedDate(maxdate))
    $("#endDate").attr("max", GetFormattedDate(maxdate))

    $('#FileUp').on('change', function (e) {
        const file = this.files[0];//將上傳檔案轉換為base64字串

        const fr = new FileReader();//建立FileReader物件
        fr.onload = function (e) {
            $('#preview').attr('src', e.target.result);//读取的结果放入圖片
        };

        // 使用 readAsDataURL 將圖片轉成 Base64
        fr.readAsDataURL(file);
    });

    $("#startDate").on('change', (event) => {
        let star = $("#startDate").val();
        let end = $("#endDate").val();
        let startime = new Date(star);
        let endtime = new Date(end);
        if (startime > endtime || ((endtime.getTime() - startime.getTime()) / 60000) < 60) {
            console.log("時間錯誤")
            $("#startDate").val("");
            $("#errSTitle").text("請輸入正確時間");
        } else {
            $("#errSTitle").text("");
        }
        console.log(star);
    })

    $("#endDate").on('change', (event) => {
        let star = $("#startDate").val();
        let end = $("#endDate").val();
        let startime = new Date(star);
        let endtime = new Date(end);
        if (startime > endtime || ((endtime.getTime() - startime.getTime()) / 60000) < 60) {
            @*|| startime.getMinutes() % 30*@
            console.log("時間錯誤");
            $("#endDate").val("");
            $("#errETitle").text("請輸入正確時間");
        } else {
            $("#errETitle").text("");
        }
        console.log(end);
        console.log()
    })


</script>