merge_EIP/Controllers/OrdermealController.cs
using merge_EIP.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace merge_EIP.Controllers
{
    public class OrdermealController : Controller
    {
        // GET: Ordermeal
        FormModelEntities db = new FormModelEntities();

        // 開團首頁
        public ActionResult Index()
        {
            if (Session["ID"] != null)
            {
                var temp = db.tOrder.Where(m => m.fStatus.Contains("結束")).ToList();
                var list = db.tOrder.Where(m => m.fStartDate <= DateTime.Today || DateTime.Today <= m.fEndDate).OrderByDescending(x => x.fStartDate).ToList();
                db.tOrder.Where(m => m.fWeek == DateTime.Today.DayOfWeek.ToString());
                ViewBag.test = DateTime.Today.DayOfWeek.ToString();
                return View(list);
            }
            else
            {
                return RedirectToAction("Logout", "Login");
            }
        }

        // 新增開團
        public ActionResult Open(string errtext)
        {
            // 如果餐廳重覆就會到這裡
            ViewBag.errtext = errtext;

            // 繫結選擇餐廳，要在顯示tOrder資料表出現 fStoreID ，並且將fStoreID 轉為 tShop資料表的 fStore，拿fStoreID做綁定。
            ViewBag.fStoreID = new SelectList(db.tShop, "fStoreID", "fStore");

            tOrder tOrder = new tOrder();
            // 為了要綁定 tOrder 這邊必須回傳 tOrder
            return View(tOrder);

            //return View(db.tShop.ToList());
        }

        [HttpPost]
        public ActionResult Open(tOrder myOrder)
        {
            tShop shop = new tShop();

            // 原本是舊有餐廳沒有值
            // 如果餐廳選擇新建餐廳有值
            if (myOrder.fNewStore != null)
            {
                // 先看有沒有重複
                var twoname = db.tShop.Where(x => x.fStore == myOrder.fNewStore).FirstOrDefault();
                if (twoname != null)
                {
                    // 不是null就是有重複的
                    return RedirectToAction("Open", new { errtext = "新建餐廳已存在" });
                }

                // 要先新建餐廳
                if (myOrder.ImageFile != null)
                {
                    string fileName = Path.GetFileNameWithoutExtension(myOrder.ImageFile.FileName);
                    string extension = Path.GetExtension(myOrder.ImageFile.FileName);
                    fileName = DateTime.Now.ToString("yymmssfff") + extension;
                    myOrder.fImagePath = "~/Menu/" + fileName;
                    fileName = Path.Combine(Server.MapPath("~/Menu"), fileName);
                    myOrder.ImageFile.SaveAs(fileName);
                }

                db.tShop.Add(new tShop { fStore = myOrder.fNewStore, fImagePath = myOrder.fImagePath });
                db.SaveChanges();

                // 如果是新建團的話，就找到剛剛新建的那一團ID存進去，或是說 更改 繫結的原設定
                myOrder.fStoreID = db.tShop.Where(x => x.fStore == myOrder.fNewStore).FirstOrDefault().fStoreID;
            }

            // 新開團
            // 因為是用 tOrder 收回來，所以會直接回收 myOrder.fStoreID，如果沒輸入的話也會
            myOrder.employeeID = Session["ID"].ToString();
            myOrder.fStartDate = DateTime.Today;
            myOrder.fStartTime = DateTime.Now.TimeOfDay;
            myOrder.fStatus = "開放中";

            db.tOrder.Add(myOrder);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        // 新增餐點
        public ActionResult Add(int? id)
        {
            //tOrderDetail detail = new tOrderDetail();
            //detail.fOrderId = id;
            if (Session["ID"] != null)
            {
                List<tOrderDetail> od = new List<tOrderDetail> { new tOrderDetail { fOrderId = (int)id, DetailEID = Session["ID"].ToString(), fFood = "", fPrice = 0, fQty = 0, fNote = "" } };

                // 找出相對的餐廳圖片
                var temp = db.tOrder.Where(m => m.fOrderId == id).FirstOrDefault();
                // 商店名
                ViewBag.temp = temp.tShop.fStore;
                // 商店照片路徑
                ViewBag.pic = temp.tShop.fImagePath;

                return View(od);
            }
            else
            {
                return RedirectToAction("Logout", "Login");
            }

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Add(List<tOrderDetail> od)
        {
            if (ModelState.IsValid)
            {
                foreach (tOrderDetail i in od)
                {
                    i.DetailEID = Session["ID"].ToString();
                    db.tOrderDetail.Add(i);
                }

                db.SaveChanges();
                ModelState.Clear();

                //od = new List<tOrderDetail> { new tOrderDetail { fId = 0, fName = Session["Name"].ToString(), fFood = "", fPrice = 0, fQty = 0, fNote = "" } };

            }
            return RedirectToAction("Index");
        }

        // 查看訂單
        public ActionResult Check(int? id)
        {
            tOrderDetail od = new tOrderDetail();

            // 撈同商店的便當(list)
            var list = db.tOrderDetail.Where(m => m.fOrderId == id).ToList();

            // 撈訂購人不重複
            var nameList = list.Select(p => p.Employee.Name).Distinct().ToList();

            // 總金額
            var total = list.Sum(x => x.fPrice * x.fQty);

            ViewBag.nameList = nameList;
            ViewBag.total = total;
            return View(list);
        }

        // 關閉開團
        public ActionResult Off(int id)
        {
            var temp = db.tOrder.Where(m => m.fOrderId == id).FirstOrDefault();
            temp.fStatus = "已結束";
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        // 管理訂單
        public ActionResult MyOrder()
        {
            if (Session["ID"] != null)
            {

                var EID = Session["ID"].ToString();

                // 取得tOrderDetail 是開放中的
                //var openOrder = db.tOrderDetail.Where(x => x.tOrder.fStatus.Contains("開放") && x.DetailEID == EID).ToList();
                var openOrder = db.tOrderDetail.Where(x => x.DetailEID == EID).OrderByDescending(x=>x.tOrder.fStartDate).ToList();


                ////所有訂單開放中的編號
                //var temp = db.tOrder.Where(m => m.fStatus.Contains("開放")).ToList();

                //// 細節
                //List<tOrderDetail> test = new List<tOrderDetail>();
                //foreach (var item in temp)
                //{
                //    // 取得Order的fId
                //    test.AddRange(db.tOrderDetail.Where(x => x.fOrderId == item.fOrderId && x.DetailEID == EID).ToList());

                //}
                //return View(test);


                return View(openOrder);
            }
            else
            {
                return RedirectToAction("Logout", "Login");
            }

        }

        // 編輯訂單
        public ActionResult Edit(int? id)
        {
            var edit = db.tOrderDetail.Where(m => m.OrderDetailId == id).FirstOrDefault();
            return View(edit);
        }

        [HttpPost]
        public ActionResult Edit(tOrderDetail od)
        {
            //ViewBag.Error = false;
            var temp = db.tOrderDetail.Where(m => m.OrderDetailId == od.OrderDetailId).FirstOrDefault();
            temp.DetailEID = Session["ID"].ToString();
            temp.fFood = od.fFood;
            temp.fPrice = od.fPrice;
            temp.fQty = od.fQty;
            temp.fNote = od.fNote;

            db.SaveChanges();
            return RedirectToAction("MyOrder");
        }

        // 刪除訂單
        public ActionResult Delete(int id)
        {
            var temp = db.tOrderDetail.Where(m => m.OrderDetailId == id).FirstOrDefault();

            db.tOrderDetail.Remove(temp);
            db.SaveChanges();
            return RedirectToAction("MyOrder");
        }
    }
}

merge_EIP/Views/Ordermeal/Add.cshtml
@model List<merge_EIP.Models.tOrderDetail>

@{
    ViewBag.Title = "Add";
}
<style>
    .form-control {
        width: 180px;
    }

    td,th {
        @*display: flex;
        flex-wrap: wrap;*@
        padding:0.5rem 1rem;
    }

    .btn-onright {
        display: flex;
        @*justify-content:right;*@
    }
</style>

<div class="container p-33">
    <br />
    <h2>點餐</h2>
    <hr />
    @using (Html.BeginForm("Add", "Ordermeal", FormMethod.Post))
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true)
        <div class=" btn-onright">
            <input type="submit" class="btn btn-FB m-1" value="送出" />
            @Html.ActionLink("取消", "Index", new { }, new { @class = "btn btn-secondary m-1" })
        </div>
        <br />
        <div class="table-responsive p-3 shadow rounded">
            <table class="" id="dataTable">
                <thead>
                    <tr>
                        <th class="">姓名</th>
                        <th class="">餐點</th>
                        <th class="">價格</th>
                        <th class="">數量</th>
                        <th class="">備註</th>
                    </tr>
                </thead>
                <tbody>
                    @if (Model != null && Model.Count > 0)
                    {

                        int j = 0;
                        foreach (var i in Model)
                        {
                            <tr>
                                @Html.HiddenFor(model => model[j].fOrderId)
                                @*<td>@Html.TextBoxFor(m => m[j].fName, htmlAttributes: new { @class = "form-control" })</td>*@
                                <td class="">@Session["Name"]</td>
                                <td class="">@Html.TextBoxFor(m => m[j].fFood, htmlAttributes: new { @class = "form-control ", required = "required" })</td>
                                <td class="">@Html.TextBoxFor(m => m[j].fPrice, htmlAttributes: new { @class = "form-control ", required = "required" })</td>
                                <td class="">@Html.TextBoxFor(m => m[j].fQty, htmlAttributes: new { @class = "form-control ", required = "required" })</td>
                                <td class="">@Html.TextBoxFor(m => m[j].fNote, htmlAttributes: new { @class = "form-control " })</td>
                                <td>
                                    @if (j > 0)
                                    {
                                        <a href="#" id="remove" class="remove"><i class="far fa-trash-alt text-secondary"></i></a>
                                    }
                                </td>
                            </tr>
                            j++;
                        }
                    }
                </tbody>
            </table>
        </div>
        <br />
        <div class="text-center">
            <a href="#" id="addNew"><i class="fas fa-plus-circle text-secondary" style="font-size:3rem"></i></a>
        </div>
        <br />
    }
    @*菜單圖片*@
    <img style="max-width:100%;width:100%" src="@Url.Content(ViewBag.Pic)" />
    <br />
    <br />
    <br />
</div>

<script src="~/Scripts/jquery.validate.js"></script>
@*<script src="~/Scripts/jquery.validate.unobtrusive.js"></script>*@
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
<script src="~/Scripts/jquery.validate-vsdoc.js"></script>
<script src="~/Scripts/jquery-3.4.1.js"></script>

<script language="javascript">
    $(document).ready(function () {

        // 添加新的列
        $("#addNew").click(function (e) {
            e.preventDefault();
            var $tableBody = $("#dataTable");
            var $trLast = $tableBody.find("tr:last");
            var $trNew = $trLast.clone();

            var suffix = $trNew.find(':input:first').attr('name').match(/\d+/);
            // 新增移除按鈕
            $trNew.find("td:last").html('<a href="#" id="remove" class="remove"><i class="far fa-trash-alt text-secondary"></i></a>');
            $.each($trNew.find(':input'), function (i, val) {
                // 取代名字
                var oldN = $(this).attr('name');
                var newN = oldN.replace('[' + suffix + ']', '[' + (parseInt(suffix) + 1) + ']');
                $(this).attr('name', newN);
                // 取代值
                var type = $(this).attr('type');
                if (type.toLowerCase() == "text") {
                    $(this).attr('value', '');
                }

                // If you have another Type then replace with default value
                $(this).removeClass("input-validation-error");

            });
            $trLast.after($trNew);

            // Re-assign Validation
            var form = $("form")
                .removeData("validator")
                .removeData("unobtrusiveValidation");
            $.validator.unobtrusive.parse(form);
        });

        // 移除
        $('body').on("click", "a.remove", function (e) {
            e.preventDefault();
            $(this).parent().parent().remove();
        });

    });
</script>

merge_EIP/Views/Ordermeal/Check.cshtml
@model IEnumerable<merge_EIP.Models.tOrderDetail>

@{
    ViewBag.Title = "Check";
}

<style>
    .row {
        justify-content: right; /*水平置中*/
    }

    .table td, .table th {
        border-top: 0.2px solid rgb(128 128 128/0.2) !important;
    }
</style>

<div class="container p-33 ">
    <br />
    <h2>查看訂單狀況</h2>
    <div class="">
        <button class="btn btn-FB m-1" onclick="outexcel()">匯出明細</button>
        @Html.ActionLink("返回", "Index", new { }, new { @class = "btn btn-secondary m-1" })
    </div>
    <br />
    @*<hr />*@

    <div class="table-responsive">
        <table class="table" id="orderall">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Employee.Name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.fFood)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.fPrice)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.fQty)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.fNote)
                </th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Employee.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.fFood)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.fPrice)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.fQty)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.fNote)
                    </td>
                </tr>
            }
        </table>
    </div>
    <div class="row">
        <div>
            @*<h3>總結</h3>*@
            <ul class="list-group list-group-flush">
                @*<tr>
                        <th>姓名</th>
                        <th>總金額</th>
                    </tr>*@


                @foreach (var person in ViewBag.nameList)
                {
                    <li class="list-group-item" style="background-color:rgb(0 0 0 /0)">
                        @person :
                        @{
                            var price = Model.Where(x => x.Employee.Name == person).Sum(y => y.fPrice * y.fQty);
                        }
                        共 @price 元
                    </li>
                }
            </ul>
            <hr />
            <div class="h3 text-center">總計 @ViewBag.total 元</div>
        </div>
    </div>


</div>

<script>
    function outexcel() {
        var html = '&lt;meta http-equiv="content-type" content="application/vnd.ms-excel; charset=UTF-8" />&lt;title>Excel&lt;/title>';
        var html = '';
        html += '';
        html += document.getElementById('orderall').outerHTML + '';
        window.open('data:application/vnd.ms-excel,' + encodeURIComponent(html));


        @*var a = document.createElement('a');
        var data_type = 'data:application/vnd.ms-excel';
        var table_div = document.getElementById('orderall').outerHTML + '';    //Your tab_text
        var table_html = table_div.replace(/ /g, '%20');
        a.href = data_type + ', ' + table_html;
        //setting the file name
        a.download = 'exported_table.xlsx';
        //triggering the function
        a.click();*@
    }
</script>

merge_EIP/Views/Ordermeal/Edit.cshtml
@model merge_EIP.Models.tOrderDetail

@{
    ViewBag.Title = "Edit";
}
<div class="container p-33">


    <br />
    <h2>編輯訂單</h2>
    <div class="">
        @Html.ActionLink("返回", "MyOrder", new { }, new { @class = "btn btn-secondary" })
    </div>
    <hr />
    <div class="row">
        <div>

            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

                <div class="form-horizontal">
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    @Html.HiddenFor(model => model.OrderDetailId)

                    <div class="form-group">
                        @Html.LabelFor(model => model.Employee.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-12">
                            @Session["Name"]
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.fFood, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-12">
                            @Html.EditorFor(model => model.fFood, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.fFood, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.fPrice, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-12">
                            @Html.EditorFor(model => model.fPrice, new { htmlAttributes = new { @class = "form-control", type = "text" } })
                            @Html.ValidationMessageFor(model => model.fPrice, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.fQty, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-12">
                            @Html.EditorFor(model => model.fQty, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.fQty, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.fNote, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-12">
                            @Html.EditorFor(model => model.fNote, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.fNote, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-12">
                            <input type="submit" value="儲存" class="btn btn-FB" />
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</div>

merge_EIP/Views/Ordermeal/Index.cshtml
@model IEnumerable<merge_EIP.Models.tOrder>

@{
    ViewBag.Title = "Index";
}
<style>
    .table td, .table th {
        border-top: 0.2px solid rgb(128 128 128/0.2) !important;
    }
</style>

@*@ViewBag.test*@

<div class="container p-33">
    <br />
    <h2>訂餐首頁</h2>
    <div class="">
        @Html.ActionLink("開團", "Open", new { }, new { @class = "btn btn-FB m-1" })
        @Html.ActionLink("管理訂單", "MyOrder", new { }, new { @class = "btn btn-FB m-1" })
        <a href="/Ordermeal" class="btn btn-FB m-1" title="刷新"><i class="fas fa-redo-alt" title="刷新"></i></a>
    </div>
    <br />
    <div class="table-responsive">
        <table class="table">
            <tr>
                <th></th>
                <th>
                    @Html.DisplayNameFor(model => model.Employee.Name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.tShop.fStore)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.fStartDate)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.fEndDate)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.fStartTime)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.fEndTime)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.fType)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.fStatus)
                </th>
                <th></th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @if (Session["ID"].ToString() == item.employeeID && item.fStatus == "開放中")
                        {
                            <a href="@Url.Action("Off")?id=@item.fOrderId" onclick="return clossbtn(event)">關閉</a>
                        }
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Employee.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.tShop.fStore)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.fStartDate)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.fEndDate)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.fStartTime)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.fEndTime)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.fType)
                    </td>
                    <td id="status">
                        @Html.DisplayFor(modelItem => item.fStatus)
                    </td>
                    @if (Html.DisplayFor(modelItem => item.fStatus).ToString() == "已結束")
                    {
                        <td>
                            @Html.ActionLink("查看餐點", "Check", new { id = item.fOrderId })
                        </td>
                    }
                    else
                    {
                        <td>
                            @Html.ActionLink("點餐", "Add", new { id = item.fOrderId }) |
                            @Html.ActionLink("查看訂單", "Check", new { id = item.fOrderId })
                        </td>
                    }
                </tr>
            }

        </table>
    </div>
</div>
<script src="~/Scripts/worklog/SwalYN.js"></script>

merge_EIP/Views/Ordermeal/MyOrder.cshtml
@model IEnumerable<merge_EIP.Models.tOrderDetail>

@{
    ViewBag.Title = "MyOrder";
}

<style>
    .table th, .table td {
        @*padding: 0.2rem 0.75rem;*@
        vertical-align:middle;
    }

    .table td, .table th {
        border-top: 0.2px solid rgb(128 128 128/0.2) !important;
    }
</style>

<div class="container p-33">
    <br />
    <h2>MyOrder</h2>
    <div class="">
        @Html.ActionLink("返回", "Index", new { }, new { @class = "btn btn-secondary" })
    </div>
    <br />
    <div class="table-responsive">
        <table class="table">
            <tr>
                <th>
                    @*@Html.DisplayNameFor(model => model.fOrderId)*@
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Employee.Name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.fFood)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.fPrice)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.fQty)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.fNote)
                </th>
                <th></th>
            </tr>

            @foreach (var item in Model)
            {

                <tr>
                    <td>
                        <a href="@Url.Action("Check")?id=@Html.DisplayFor(modelItem => item.fOrderId)">查看</a>
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Employee.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.fFood)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.fPrice)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.fQty)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.fNote)
                    </td>
                    <td>
                        @if (item.tOrder.fStatus.Contains("開放"))
                        {
                            <a href="@Url.Action("Edit")?id=@item.OrderDetailId" class="btn btn-FB m-1">編輯</a>
                            <a href="@Url.Action("Delete")?id=@item.OrderDetailId" class="btn btn-secondary m-1" onclick="return delbtn(event)"><i href="@Url.Action("Delete")?id=@item.OrderDetailId" class="far fa-trash-alt" style="color:white;"></i></a>
                        }
                    </td>
                </tr>
            }
        </table>
    </div>
</div>
<script src="~/Scripts/worklog/SwalYN.js"></script>